export const browserCoreExamples = [
  "unmaskbot browser status",
  "unmaskbot browser start",
  "unmaskbot browser stop",
  "unmaskbot browser tabs",
  "unmaskbot browser open https://example.com",
  "unmaskbot browser focus abcd1234",
  "unmaskbot browser close abcd1234",
  "unmaskbot browser screenshot",
  "unmaskbot browser screenshot --full-page",
  "unmaskbot browser screenshot --ref 12",
  "unmaskbot browser snapshot",
  "unmaskbot browser snapshot --format aria --limit 200",
  "unmaskbot browser snapshot --efficient",
  "unmaskbot browser snapshot --labels",
];

export const browserActionExamples = [
  "unmaskbot browser navigate https://example.com",
  "unmaskbot browser resize 1280 720",
  "unmaskbot browser click 12 --double",
  'unmaskbot browser type 23 "hello" --submit',
  "unmaskbot browser press Enter",
  "unmaskbot browser hover 44",
  "unmaskbot browser drag 10 11",
  "unmaskbot browser select 9 OptionA OptionB",
  "unmaskbot browser upload /tmp/file.pdf",
  'unmaskbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "unmaskbot browser dialog --accept",
  'unmaskbot browser wait --text "Done"',
  "unmaskbot browser evaluate --fn '(el) => el.textContent' --ref 7",
  "unmaskbot browser console --level error",
  "unmaskbot browser pdf",
];
